Here is the Elm language source for calculating and printing out a series of numbers' factorials from 0 to 12 (inclusive):

factorial : Int -> Int
factorial n = if n == 0 then 1 else product [n..1] // fact(n-1) * n
             where sum_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: product [from..upper]  // expr1 * ...
             where sum_a = `sum `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, rangeUpperBound (b+2), and count c from to the upper bound of numbers upto 'c' are used. This is equivalent in Elm syntax as: sum [from..upper] +...  // expr1 * ...
             where product_a = `product `rangeFromTo a b, range